### ISSUE TITLE
Instantiate heavy class in an isolate and access its methods (including parameters) from the main thread later.

### ISSUE THREAD

**Issue by jorgegaticav** [GlebBatykov/theater#1]
Hi, 
I am trying to figure a multiprocessing problem in dart, and I would like to ask you if your library would be useful in this case.
I am using a class that depends on native code using dart ffi. This class is similar to a server that deals with heavy data (let's say video, big images, etc), has a heavy initialization and heavy requests methods which I need to run at the same time multiple times, therefore, I need to run it in a way that doesn't block the main thread.
I have tried to  instantiate the class in the main thread and then run its methods using isolate but it fails because the parameters include aPointers variables (from ffi). 
Therefore, my idea is to find a way to instantiate the class in an isolate from the beginning, and access it methods later through messages which should return the processed data to the main thread.
Is that possible using your library?

**Comment by GlebBatykov** [comment]
Hi, if I understood you correctly, you are using some class that uses ffi and performs some heavy operations. You want to execute it in another isolate and get the computation result in the main isolate.

You can do this with just isolates or with my package.

An example of how you can use my package to create something in another isolate (in my package - in an actor), call something upon request (sending a message) and send a response to the one who sent the message.

In the example, class CMath is a class that implements mathematical operations using ffi.

```dart
class SqrtActor extends UntypedActor {
  late final CMath _math;

  @override
  Future<void> onStart(UntypedActorContext context) async {
    _math = CMath();

    context.receive<double>((message) async {
      return MessageResult(data: _math.sqrt(message));
    });
  }
}

void main() async {
  var system = ActorSystem('test_system');

  await system.initialize();

  var ref = await system.actorOf('sqrt_actor', SqrtActor());

  var subscription = ref.sendAndSubscribe(2.toDouble());

  subscription.onResponse((response) {
    if (response is MessageResult) {
      print(response.data);
    }
  });
}
```

If you have any more questions, I will be happy to answer them.

**Comment by jorgegaticav** [comment]
@GlebBatykov this is exactly what I was looking for! Thank you very much, it works perfect!
